spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.1.3:3306/csii_dbus?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


# 开启所有端点允许HTTP查看
management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.csii.commons.entities  #所有Entity别名类所在包

logging:          #扫描dao层，保证SQL指令在控制台 输出
  level:
    com:
      csii:
        regist:
          dao: trace